Add styles
j-tee/bookstore pull request #5
Opened 2022-11-11 19:25 UTC by j-tee

## In this milestone:
- Open the project *Bookstore CMS*.
- Use the information detailed in Zeplin to style the website.
- Your final design is comparable to Zeplin's design.

2022-11-11 21:14 UTC, Munsa1 requested changes
Hi @j-tee, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow
## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be nice if you could add the user profile icon to your design which is located to the right of the categories heading in the `nav` section in the original design, this will make your design match the given design more.


Given design
![image](https://user-images.githubusercontent.com/81932478/201431463-3870fa16-55ab-41c3-874a-b1e52e33c585.png)

Your design
![image](https://user-images.githubusercontent.com/81932478/201431500-c60f7ebf-408f-44ef-a880-d6be676ec93a.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-11 21:14 UTC, Munsa1 commented on src/components/Book.js
> +        <div>&nbsp;</div>
- [ ] Kindly try to match your design to look like the given design as much as possible. The circular progress bar is missing from your design, so is the progress information to the far left of the original design, such as the chapter e.t.c., kindly add it.

Given design
![image](https://user-images.githubusercontent.com/81932478/201429878-3ba19cc6-3fb0-4d0b-b4f5-c33aa237c517.png)

Your design
![image](https://user-images.githubusercontent.com/81932478/201430015-25e576e9-2315-4cef-beb9-33810e74d8b2.png)

2022-11-11 21:14 UTC, Munsa1 commented on src/App.css
> +  background-color: #fafafa;
- [ ] Dry principles of CSS code are encouraged here, you have this background color being applied in another class in line 31 causing repetition. Kindly follow DRY principles by creating a class with the background color that can be reused in the components, [refer to this tutorial for more help](https://speckyboy.com/good-bad-css-practices/)

2022-11-12 08:52 UTC, OLIPLICHE approved these changes
Hi @j-tee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Implemented the changes 👏 👏
- The App is working fine👏 👏
- Linter is green (the last commit have a green check mark (✅)) 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 08:52 UTC, OLIPLICHE commented on src/App.js
>          <Route path="/category" element={<Category />} />
- Well Done 🥇 🥇 🥇 
- 
![Capture](https://user-images.githubusercontent.com/63972670/201466572-999697c9-5315-41ce-b675-1990c4ef18ee.PNG)

2022-11-14 11:14 UTC, merged